### ISSUE TITLE
[main_page]최근 글 누를시 detail 출력

### ISSUE THREAD

**Issue by dlwlsrnjs** [0sunzero0/TDP#73]
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>content</title>

</head>
<body>
<p>content</p>
{{content}}
</body>
</html>

##main page

function listing() {
        $.ajax({
                type: "GET",
                url: "/home_listing",
                data: {},
                success: function (response) {
                    let home_til = response['home_til'];
                    for (let i = 0; i < 4; i++) {
                        let title = home_til[i]['til_title'];
                        let user = home_til[i]['til_user'];
                        let content = home_til[i]['til_content'];
                        let day = home_til[i]['til_day'];
                        let temp_html = `
                <div class="col" id="cards-box">
               <div class="card">
                <h5 class="card-subtitle">${user}</h5>
               <div class="card-body">
                <h5 class="card-title">${title}</h5>
                <p class="card-text">${content}</p>
                <p class="card-time">${day} </p>
                </div>
                  </div>
`
                        $('#board-main').append(temp_html)
                    }
                }
            }
        )
    }

`

**Comment by 0sunzero0** [comment]
3차 프로젝트로 이동
